#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : requests-mock
Version  : 1.5.0
Release  : 27
URL      : http://pypi.debian.net/requests-mock/requests-mock-1.5.0.tar.gz
Source0  : http://pypi.debian.net/requests-mock/requests-mock-1.5.0.tar.gz
Summary  : Mock out responses from the requests package
Group    : Development/Tools
License  : Apache-2.0
Requires: requests-mock-python3
Requires: requests-mock-python
Requires: Sphinx
Requires: fixtures
Requires: pytest
Requires: python-mock
Requires: requests
Requires: six
Requires: testrepository
Requires: testtools
BuildRequires : extras
BuildRequires : fixtures
BuildRequires : pbr
BuildRequires : pip

BuildRequires : python-mock
BuildRequires : python3-dev
BuildRequires : requests
BuildRequires : setuptools
BuildRequires : six
BuildRequires : testtools

%description
requests-mock
        ===============================

%package python
Summary: python components for the requests-mock package.
Group: Default
Requires: requests-mock-python3

%description python
python components for the requests-mock package.


%package python3
Summary: python3 components for the requests-mock package.
Group: Default
Requires: python3-core

%description python3
python3 components for the requests-mock package.


%prep
%setup -q -n requests-mock-1.5.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1526164101
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
py.test-2.7 --verbose py2 || :
%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
